[workspace]
resolver="2"
members=[
    "crates/behave",
    "crates/collide",
    "crates/platformer"
]

[workspace.dependencies]
bevy = {git="https://github.com/bevyengine/bevy.git", rev="5508915e9bffb4d7a0eccfa2281313b21c2f538d", default-features=false, features = ["dynamic_linking"]}