[package]
name = "collision"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
tinyvec = "1.6.0"
enum_dispatch = "0.3.12"
static_assertions = "1.1.0"

[dev-dependencies]
bevy = { workspace = true, features=["default"] }