[package]
name = "nvm_platformer"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true, features=["default"] }
tinyvec = "1.6.0"
nvm_collide = { path = "../collide/" }
nvm_behave = { path = "../behave/" }
